### ISSUE TITLE
`data.table` re-write of `slice()`

### ISSUE THREAD

**Issue by dylanbeaudette** [ncss-tech/aqp#115]
## A Plan
 1. finish  `dice` 
 2. test / document `dice`
 3. deprecate `slice`
 4. fix many affected functions / documentation  (note `slice` max + 1 convention)
 5. enable slicing shortcut through the SPC `k-index` (maybe)

## TODO
 - [x] finish tests
 - [ ] side/side comparisons with `slice` in all aqp functions (this will take time, and aqp 2.0 is not backwards compatible)
 - [x] sometimes `fm = 0:z ~ .` results in `z+1` slices (bug related to filling to bottom of z-index, z +1)
 - [x] NA-padding to depth via `fillHzGaps` (default = FALSE), important for `slab` and `profile_compare`
    - [x] fully-integrate newly optimized `fillHzGaps`, consider separate arguments to control filling / padding
 - [x] formula interface (backwards compatibility, less data to push around):
    - [x] slice selection via integer vector
    - [x] variable selection via NSE `var1 + var2 + ...`
    - [x] ERROR when asking for slices entirely within horizon gaps or invalid horizons (addressed in #205, pending optimization)
 - [x] .pctMissing eval (new function)
    - [x] optimize with `data.table` (see warnings...)
    - [x] DT warnings related `:=` (see below)
 - [x] ERRORS on NA bottom depth (consider `repairMissingHzDepths()`)
 - [x] horizon depth logic errors: flag (`@metadata`) / subset:
    - [x] horizon level `byhz = TRUE` (should eventually do gap-filling with NA records #205)
    - [x] profile level `byhz = FALSE`
 - [ ] ~~integrate into `slab()` (problems as of 2022-01-04), or integrate into slab-rewrite (better).~~ (different PR / issue)

## Long-Term
 - [ ] future optimization `setindex()` vs. `setkey()` <-- this sorts the data (probably not worth the extra effort)
 - [ ] overlapping (A/E type) horizons (#88)

## Updates
 * 2021-02-11: just about ready for use. This is not a direct replacement for `slice`, maybe introduce now and phase-in by aqp 2.0.
 * 2022-01-04: much more robust, direct replacement for `slice` in most cases. will attempt to change all `slice` → `dice` in the SPC introduction and see what happens. a messages is now printed when using `slice`, will be deprecated in aqp 2.0.

See draft code for [`dice()`](https://github.com/ncss-tech/aqp/blob/master/misc/sandbox/dice.R). This is about 6x faster than the current implementation of `slice`, with a lower memory footprint as well.

**Comment by brownag** [comment]
Reprex for `slab()` on data.table-SPC slots

``` r
library(aqp, warn=FALSE)
#> This is aqp 1.27

data(sp4)
sp4$name <- factor(sp4$name)

depths(sp4) <- id ~ top + bottom

# works
a <- slab(sp4, ~ name)
head(a)
#>   variable all.profiles   A  A1  A2  AB ABt  Bt Bt1 Bt2 Bt3 top bottom
#> 1     name            1 0.9 0.1 0.0 0.0 0.0 0.0 0.0   0   0   0      1
#> 2     name            1 0.9 0.1 0.0 0.0 0.0 0.0 0.0   0   0   1      2
#> 3     name            1 0.8 0.0 0.1 0.0 0.0 0.0 0.1   0   0   2      3
#> 4     name            1 0.4 0.0 0.1 0.0 0.1 0.1 0.3   0   0   3      4
#> 5     name            1 0.3 0.0 0.1 0.0 0.1 0.1 0.4   0   0   4      5
#> 6     name            1 0.3 0.0 0.0 0.1 0.1 0.1 0.4   0   0   5      6
#>   contributing_fraction
#> 1                     1
#> 2                     1
#> 3                     1
#> 4                     1
#> 5                     1
#> 6                     1

# does not work
data(sp4)
sp4$name <- factor(sp4$name)
sp4 <- data.table::as.data.table(sp4)
depths(sp4) <- id ~ top + bottom

b <- slab(sp4, ~ name)
#> Error in h[, vars]: incorrect number of dimensions
```

**Comment by dylanbeaudette** [comment]
Yup, `slab` and many other functions in {aqp} are not `data.table` aware. There are going to be a lot of `x[, vars]` cases that need to be generalized.

**Comment by brownag** [comment]
I think I would lean towards your option 1, based on recent experiences we all have had

**Comment by dylanbeaudette** [comment]
Me too. Hegemony for the tidyverse and all.

Here is the evolving plan: finish `dice` → deprecate `slice` → fix many affected functions / documentation → enable slicing shortcut through the SPC `k-index` (maybe).

**Comment by dylanbeaudette** [comment]
Making progress, plenty of room to optimize, likely at the `mapply` step.

```
# A tibble: 3 x 13
  expression     min  median `itr/sec` mem_alloc `gc/sec` n_itr  n_gc total_time result memory          time    gc       
  <bch:expr> <bch:t> <bch:t>     <dbl> <bch:byt>    <dbl> <int> <dbl>   <bch:tm> <list> <list>          <list>  <list>   
1 slice        15.8s   15.8s    0.0634     1.6GB     1.65     1    26      15.8s <NULL> <Rprofmem[,3] … <bch:t… <tibble …
2 dice_fm      10.3s   10.3s    0.0972   530.6MB     2.91     1    30      10.3s <NULL> <Rprofmem[,3] … <bch:t… <tibble …
3 dice         10.1s   10.1s    0.0988   459.1MB     2.08     1    21      10.1s <NULL> <Rprofmem[,3] … <bch:t… <tibble …
```

**Comment by dylanbeaudette** [comment]
`slice` pads all profiles with NA to the maximum depth of slicing (specified in `fm`), `dice` does not.

![image](https://user-images.githubusercontent.com/624277/108615341-dda94700-73b7-11eb-9c48-c4e08fc34604.png)

I'm going to implement this as an option in `dice`, but there are only a couple of cases where the extra work / bloat are worth it:
 * functions expecting it (`slab`, `profile_compare` at the moment)
 * expectation about the SPC `j` index post-slicing/dicing

**Comment by dylanbeaudette** [comment]
Crap, when asking for a slice or range of slices that fall entirely within a horizon gap or horizon with bogus depths there is an error. This happens because the re-packed horizons are missing a profile ID that exists in site.

```r
data(sp4)
depths(sp4) <- id ~ top + bottom

sp4$top[1:2] <- NA

## this throws an error
d <- dice(sp4, fm = 5 ~ ., byhz = TRUE)

## this works, but a profile is dropped
d <- dice(sp4, fm = 5 ~ ., byhz = FALSE)

## this breaks at mapply step
d <- dice(sp4, fm = 5 ~ ., strict = FALSE)

# old slice, NA returned
s <- slice(sp4, fm = 5 ~ .)

profile_id(d) <- sprintf("%s-dice", profile_id(d))
z <- combine(s, d)

par(mar = c(0, 0, 0, 0))
plotSPC(z[1:8, ], color = 'Ca')
```

**Comment by dylanbeaudette** [comment]
With the addition of `growEmptyHz`, `dice` can now pad with NA. Note that this is still not quite the same as the output from `slice` which always gave one extra slice. This convention will not be carried forward.

![image](https://user-images.githubusercontent.com/624277/108957433-50b7f500-7626-11eb-94ae-4196aa07c707.png)

**Comment by dylanbeaudette** [comment]
Encountering DT warnings when `.pctMissing = TRUE`:

```
 In `[.data.table`(res, , `:=`(.pctMissing, rowSums(is.na(res[, .SD,  :
  Invalid .internal.selfref detected and fixed by taking a (shallow) copy of the data.table so that := can add this new column by reference. At an earlier point, this data.table has been copied by R (or was created manually using structure() or similar). Avoid names<- and attr<- which in R currently (and oddly) may copy the whole data.table. Use set* syntax instead to avoid copying: ?set, ?setnames and ?setattr. If this message doesn't help, please report your use case to the data.table issue tracker so the root cause can be fixed or this message improved.
```

**Comment by dylanbeaudette** [comment]
> Crap, when asking for a slice or range of slices that fall entirely within a horizon gap or horizon with bogus depths there is an error. This happens because the re-packed horizons are missing a profile ID that exists in site.

No longer a problem, the `fillHzGaps` can help with gaps in the horizon depth sequence but still needs optimization.

![image](https://user-images.githubusercontent.com/624277/109535765-c6caba80-7a71-11eb-8ae8-1fd1994ae6a9.png)


```r
data(sp4)
depths(sp4) <- id ~ top + bottom

# corrupt 2nd horizon of colusa
sp4$top[2] <- NA

# remove invalid horizons
x <- HzDepthLogicSubset(sp4, byhz = TRUE)

# fill hz gaps
x <- fillHzGaps(x)

# works after gap-filling
d <- dice(x, fm = 0:15 ~ ., byhz = TRUE)

# old slice, NA returned
s <- slice(sp4, fm = 0:15 ~ .)

profile_id(d) <- sprintf("%s-dice", profile_id(d))
z <- combine(s, d)

par(mar = c(0, 0, 0, 0))
plotSPC(z[1:8, ], color = 'Ca')
```

**Comment by dylanbeaudette** [comment]
> Encountering DT warnings when `.pctMissing = TRUE`:
> 
> > In `[.data.table`(res, , `:=`(.pctMissing, rowSums(is.na(res[, .SD,  :
> > Invalid .internal.selfref detected and fixed by taking a (shallow) copy of the data.table so that := can add this new column by reference. At an earlier point, this data.table has been copied by R (or was created manually using structure() or similar). Avoid names<- and attr<- which in R currently (and oddly) may copy the whole data.table. Use set* syntax instead to avoid copying: ?set, ?setnames and ?setattr. If this message doesn't help, please report your use case to the data.table issue tracker so the root cause can be fixed or this message improved.

This is now addressed / tested by using `set()` vs. `:=` notation. Still not sure why this was happening, but no more warnings + same results and possible smaller memory footprint.

**Comment by dylanbeaudette** [comment]
Latest benchmarks using 10,000 random profiles.

```
  expression                  min   median `itr/sec` mem_alloc `gc/sec` n_itr  n_gc total_time
1 slice_strict             19.81s   19.81s    0.0505    1.58GB    0.656     1    13     19.81s
2 slice                    20.76s   20.76s    0.0482    1.57GB    0.482     1    10     20.76s
3 dice                      4.92s    4.92s    0.203   540.95MB    1.22      1     6      4.92s
4 dice_byhz                   13s      13s    0.0769  547.78MB    1.38      1    18        13s
5 dice_fm                   4.72s    4.72s    0.212   680.66MB    1.27      1     6      4.72s
6 dice_fm_nofill            6.06s    6.06s    0.165   680.66MB    1.16      1     7      6.06s
7 dice_no_chk               4.26s    4.26s    0.235   535.34MB    1.41      1     6      4.26s
8 dice_no_chk_pctmissing    4.53s    4.53s    0.221   792.12MB    1.32      1     6      4.53s
```
