### ISSUE TITLE
AWC estimation by LUT

### ISSUE THREAD

**Issue by dylanbeaudette** [ncss-tech/aqp#212]
It would be great to have our LUT-based approach to estimating AWC ranges by texture class, fragment volume, SOM available in an {aqp} function. Thanks @brownag for getting us close: [estimateAWC](https://github.com/ncss-tech/aqp/tree/estimateAWC).

## TODO
- [ ] develop test/evaluation dataset
- [ ] parity with NASIS if possible
- [ ] compare with a couple of manual estimates

**Comment by brownag** [comment]
In many cases `estimateAWC()` gives values similar to those expected by NASIS validations on aggregate component data. The validation "allowed ranges" are calculated from the (_usually_ also calculated) water retention difference. On occasion I need to adjust some values (often the LOW) due to slight offsets in 2nd decimal place (usually 0.01 off from expected limit) in order to pass validation. 

I am not sure that we can achieve NASIS parity (i.e. `estimateAWC()` always produce values that "pass") without also having estimates of parameters like 1/3 bar bulk density and sieve/fragment size ranges that figure into the water content calculations. Reproducing the cascade of NASIS pedotransfer functions for water content related inputs might be worth revisiting in https://github.com/ncss-tech/pedotransfR ... however a simpler approach using generalized horizons to estimate organic matter content and bulk density might get us most of the way there.

**Comment by dylanbeaudette** [comment]
Finally working my way back to this issue. Some observations:

   * `estimateAWC('si', omcl = 1)` returns `NA`, seems like "silt" texture class is missing from the LUT.
   * I need to study the code more carefully, but I think that `approxfun()` would be a more generic solution to supplying an aggregate `FUN`. I'll work on an example after further study.
   * Preliminary comparisons between `estimatesAWC()` and a simplistic AWC derived from the `ROSETTA.centroids` can be found in [`misc/estimateAWC-vs-ROSETTA-centroids.R`](https://github.com/ncss-tech/aqp/misc/estimateAWC-vs-ROSETTA-centroids.R)

![image](https://user-images.githubusercontent.com/624277/131605366-11092eed-bf54-4bd1-b9c8-6e56c1d38007.png)
![image](https://user-images.githubusercontent.com/624277/131605414-af992b0f-d174-4f04-9792-8f6077a2484f.png)
