### ISSUE TITLE
Develop new spectral library from the Munsell Color Atlas 

### ISSUE THREAD

**Issue by dylanbeaudette** [ncss-tech/aqp#231]
https://www.pantone.com/munsell-book-of-color-matte-edition

Initially at 10nm resolution, using our CM-700d spectrophotometer.

**Comment by dylanbeaudette** [comment]
Book has been ordered, spectra will be collected this fall.

### TODO

- [ ] write simple SOP and calibration schedule
- [ ] collect spectra from all chips, including 10x / single chip / hue for estimates of precision
- [ ] interpolate spectra to odd chroma
- [ ] re-build reference spectra database / documentation in `aqp`
- [ ] evaluate current testing
- [ ] cross-reference with reference XYZ values in `munsell` LUT
