### ISSUE TITLE
Refactor all Munsell LUT creation code, munsell2rgb, rgb2munsell

### ISSUE THREAD

**Issue by dylanbeaudette** [ncss-tech/aqp#251]
Moving #178 and #249 into this issue.

## TODO

- [ ] ~~adapt old color space transform code → `grDevices::convertColor()` and test~~ retaining manual conversion for now
- [x] scan neutral chips and prepare as DF with hue, value, chroma, [sRGB], [LAB]
- [x] integrate new neutral chips
- [x] interpolate 2.5 values
- [x] check new vs. old
- [x] `munsell2rgb()` should no longer round 2.5 values
- [x] interpolate reference spectra for 2.5 value and 1 chroma
- [x] check `rgb2munsell()` for corner cases related to 2.5 values
- [x] check `getClosestMunsellChip()`
- [x] check `equivalentMunsellChips()` and supporting data
- [x] previous tests
- [x] new tests
- [x] PMS LUT and tests
- [x] document any changes

## Notes
  * xyY **Y** values are now truncated to 100 before rescaling → [0,1], previously **Y** values were only divided by 100.
  * subtle shift between old vs. new: mostly `value == 1`.
  * new neutral colors are 10-30 dE00 off from original estimates
  * manual conversion from xyY → sRGB and chromatic transform seem to work fine

**Comment by dylanbeaudette** [comment]
No rush, @brownag please have a look at `equivalentMunsellChips()` and supporting data when you get a chance. The contents of the `munsell` LUT have changed ever so slightly.
